version: '3.8'

networks:
  energy-network:
    external: true  # Netzwerk wird vorausgesetzt, muss vorher erstellt werden

services:
  energy-monitor-backend:
    image: energy-monitor-backend:latest
    container_name: energy-monitor-backend
    networks:
      - energy-network
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DB_HOST: 10.55.10.9
      DB_USER: energy-app
      DB_PASSWORD: energy-app
      DB_NAME: Solaranlage
      PORT: 3003

  energy-monitor-frontend:
    image: energy-monitor-frontend:latest
    container_name: energy-monitor-frontend
    networks:
      - energy-network
    restart: unless-stopped
    ports:
      - "4200:80"
